# Generated by Django 3.1.1 on 2021-01-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0009_auto_20210108_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='map1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='map2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
